package com.haulmont.testtask.web.orderForm;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderEdit extends VerticalLayout {
    protected TextField description;
    protected HorizontalLayout clientBoxH;
    protected HorizontalLayout mechanicBlocH;
    protected DateField dateCreature;
    protected DateField dateOfWork;
    protected TextField cost;
    protected HorizontalLayout statusBoxH;
    protected Button save;
    protected Button cancel;

    public OrderEdit() {
        Design.read(this);
    }
}
